### ISSUE TITLE
https://github.com/tchasinga/space-travelers

### ISSUE THREAD

**Issue by tchasinga** [tchasinga/space-travelers#25]
in this project we've two members :
[tchasinga](https://github.com/tchasinga)
[Log-benjamin](https://github.com/Log-benjamin)

**Comment by DammyShittu** [comment]
Hi @tchasinga and @Log-benjamin,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the kanban link in the issue

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
